### PR TITLE
Upgrade bootstrap-sass dependency to 3.3.5. 

### PR DESCRIPTION
**Pull request by OzzieOrca**
Fix call to pagination-size mixin that didn't have line-height parameter.

Got an error about the above during compile and fixed it.
Haven't tested any other parts of the framework after upgrade but might do more testing if I continue to use it.

### CODE REVIEW

**Comment by mattgasior** [comment]
@OzzieOrca – sorry for the delayed response on this – we were on some deadlines last week and this fell through the cracks. We will need to test what the upgrade to 3.3.5 will do to our current project in production before we can pull this in. 

@thejamesdempsey, is there an easy way to test this in cruorgaem6 without pulling this in and running bower update? I'm not totally familiar with the best way to do that.

**Comment by thejamesdempsey** [comment]
@mattgasior I am not sure I recall a better way to go about testing it. I would say to make sure it runs on the crubrand site.

**Comment by elikem** [comment]
@thejamesdempsey By crubrand site you mean the style guide? It runs just fine (compiles and no visual issues I see).

If this is all we need then we can do a merge.

**Comment by OzzieOrca** [comment]
Can this be merged? I realized I used it in https://github.com/CruGlobal/godtools-admin/blob/master/bower.json#L11 which is now live. It would be better if that pointed to the real repo. We probably need to bump the version. Seems like you guys have just been bumping the minor version. I can commit and tag that if you want.

**Comment by elikem** [comment]
@OzzieOrca this is fine to merge, go ahead. Do bump the the version.

**Pull request merged**
